spring:
  application:
    name: glucocloud-api

  # H2 Database for local development
  datasource:
    url: jdbc:h2:mem:glucocloud
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890123456789012345678901234567890
  expiration: 86400000 # 24 hours in milliseconds

# Server Configuration
server:
  port: 8080

# Logging
logging:
  level:
    com.glucocloud.api: DEBUG
    org.springframework.security: DEBUG

---
# Production profile (for Render deployment)
spring:
  config:
    activate:
      on-profile: production

  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  h2:
    console:
      enabled: false

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    com.glucocloud.api: INFO
    org.springframework.security: WARN

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true